class CreateDartSalesPricingCurrents < ActiveRecord::Migration[5.1]
  def change
    create_table :dart_sales_pricing_currents do |t|
      t.integer :invoice_numb
      t.string :sls_rep
      t.string :AM_OF
      t.integer :disregard_catch_wgt
      t.string :AM_ST
      t.string :owner
      t.string :order_stat
      t.string :cost_ctr
      t.string :order_numb
      t.string :rel_numb
      t.string :item_no
      t.string :cust_code
      t.string :bus_name
      t.string :sales_type
      t.string :shipto_code
      t.string :cust_group
      t.string :cust_subgroup
      t.string :met_of_ship
      t.string :carr_code
      t.string :route_code
      t.string :rep1
      t.date :order_date
      t.date :dueout_date
      t.date :sale_date
      t.date :pk_prt_date
      t.string :pick_numb
      t.string :part_code
      t.string :alt_part1
      t.string :part_status
      t.string :part_desc
      t.string :part_grp
      t.string :part_subgrp
      t.float :catch_wt
      t.integer :qty
      t.integer :ship_qty
      t.string :picker_id
      t.string :shipadd1
      t.string :shipcity
      t.string :shipst
      t.string :uom
      t.float :item_wgt
      t.string :item_sales_acct
      t.float :item_list_price
      t.float :item_price
      t.float :item_ntprice
      t.float :ext_price
      t.integer :qty_sold
      t.float :total_lbs
      t.float :sales_dol
      t.string :lot_invitem
      t.string :lot_shipitem
      t.string :day_of_month
      t.string :day_name
      t.string :week_of_year
      t.string :month_name
      t.string :year_val
      t.float :stnd_matl_cost
      t.float :gp_dol_xpl
      t.float :tot_std_cost
      t.float :gp_dol_lot
      t.string :trailer_location
      t.date :date_entered
      t.time :time_entered
      t.integer :qty_invitem
      t.string :orig_order_numb
      t.string :orig_rel_numb
      t.string :invc_type
      t.string :item_priceid
      t.float :numfld2
      t.string :price_id
      t.float :part_price
      t.string :part_uom
      t.date :eff_date
      t.date :end_date
      t.float :uom_conv
      t.float :alt_list_price
      t.string :Price_Sheet_Type
      t.string :team
      t.string :channel
      t.string :price_id_04
      t.float :part_price_04
      t.string :part_uom_04
      t.date :eff_date_04
      t.date :end_date_04
      t.float :alt_list_price_04
      t.float :base
      t.date :created_at
      t.date :updated_at
      t.string :Fiscal_Year
      t.string :Fiscal_Month

      t.timestamps
    end
  end
end
